//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbstractFabric.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AbstractFabric.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя стиля недолжно содержать пустоты или null!.
        /// </summary>
        public static string EmptyStyleName {
            get {
                return ResourceManager.GetString("EmptyStyleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пустое название стиля!.
        /// </summary>
        public static string EmptyStyleTitle {
            get {
                return ResourceManager.GetString("EmptyStyleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка валидации аргумента.
        /// </summary>
        public static string ErorArgumentTitle {
            get {
                return ResourceManager.GetString("ErorArgumentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка валидации типа!.
        /// </summary>
        public static string ErrorGenericType {
            get {
                return ResourceManager.GetString("ErrorGenericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка создания предмета:  Нереализованная  модель  предмета!.
        /// </summary>
        public static string ErrorItem {
            get {
                return ResourceManager.GetString("ErrorItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно создать объект кресла: Одно или несколько свойств содержат null или пустоту или значение меньше 1.
        /// </summary>
        public static string ErrorItemArmChairType {
            get {
                return ResourceManager.GetString("ErrorItemArmChairType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно создать объект стула: Одно или несколько свойств содержат null или пустоту или значение меньше 1.
        /// </summary>
        public static string ErrorItemChairType {
            get {
                return ResourceManager.GetString("ErrorItemChairType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно создать объект  дивана: Одно или несколько свойств содержат null или пустоту или значение меньше 1.
        /// </summary>
        public static string ErrorItemSofaType {
            get {
                return ResourceManager.GetString("ErrorItemSofaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка создания нового предмета!.
        /// </summary>
        public static string ErrorItemTitle {
            get {
                return ResourceManager.GetString("ErrorItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя предмета или его стиль недолжен содержать пустоту или null значение.
        /// </summary>
        public static string ErrorNameArgument {
            get {
                return ResourceManager.GetString("ErrorNameArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка валидации свойства!.
        /// </summary>
        public static string ErrorPropertyTitle {
            get {
                return ResourceManager.GetString("ErrorPropertyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Несуществующий стиль объекта.
        /// </summary>
        public static string ErrorStyleGenericType {
            get {
                return ResourceManager.GetString("ErrorStyleGenericType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Высота и ширина должны быть больше или равны 1.00 метру.
        /// </summary>
        public static string ErrorWidthAndHeightMessage {
            get {
                return ResourceManager.GetString("ErrorWidthAndHeightMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение не должно равнятся null!.
        /// </summary>
        public static string NullItemType {
            get {
                return ResourceManager.GetString("NullItemType", resourceCulture);
            }
        }
    }
}
